// Usage: node bench/longsession/range-table.mjs results/<runId>
// Writes range-table.md: arm B cost relative to arm A per N, with the min–max of the per-repetition ratio.
// Session cost uses the same definition as summarize.mjs (conversation turns only, ok calls, complete sessions).
import { readFileSync, writeFileSync } from "node:fs"
import { join, resolve, basename } from "node:path"

const dir = resolve(process.argv[2])
const rows = readFileSync(join(dir, "results.jsonl"), "utf8").trim().split("\n").filter(Boolean).map(JSON.parse)

const sessions = new Map()
const key = (r) => `${r.scenario}|${r.N}|${r.arm}|${r.rep}`
for (const r of rows) {
  if (!sessions.has(key(r))) sessions.set(key(r), { N: r.N, arm: r.arm, rep: r.rep, cost: 0, recallOk: 0, recallN: 0, status: "incomplete" })
  const s = sessions.get(key(r))
  if (r.kind === "session") s.status = r.status
  if (r.kind === "turn" && r.status === "ok") s.cost += r.costUsd
  if (r.kind === "recall") {
    s.recallN++
    if (r.correct) s.recallOk++
  }
}

const done = [...sessions.values()].filter((s) => s.status === "complete")
const mean = (xs) => xs.reduce((a, b) => a + b, 0) / xs.length
const meanCost = (N, arm, rep) => mean(done.filter((s) => s.N === N && s.arm === arm && (rep == null || s.rep === rep)).map((s) => s.cost))

const Ns = [...new Set(done.map((s) => s.N))].sort((a, b) => a - b)
const reps = [...new Set(done.map((s) => s.rep))].sort((a, b) => a - b)
const pct = (x) => `${x >= 0 ? "+" : "−"}${Math.abs(x * 100).toFixed(1)}%`

const lines = [
  `# Range table — ${basename(dir)}`,
  "",
  "Generated by `bench/longsession/range-table.mjs` from `results.jsonl`. Do not edit by hand.",
  "",
  "Ratio = mean arm-B (belcore) session cost ÷ mean arm-A (full history) session cost. Range = min–max of that ratio computed separately for each repetition.",
  "",
  "| N | B/A cost | change | per-rep min | per-rep max | reps |",
  "|---|---|---|---|---|---|",
]
for (const N of Ns) {
  const ratio = meanCost(N, "B") / meanCost(N, "A")
  const perRep = reps.map((rep) => meanCost(N, "B", rep) / meanCost(N, "A", rep)).filter(Number.isFinite)
  const lo = perRep.length === reps.length ? Math.min(...perRep).toFixed(3) : "없음"
  const hi = perRep.length === reps.length ? Math.max(...perRep).toFixed(3) : "없음"
  lines.push(`| ${N} | ${ratio.toFixed(3)} | ${pct(ratio - 1)} | ${lo} | ${hi} | ${perRep.length} |`)
}

const recall = (N, arm, rep) => {
  const ss = done.filter((s) => s.N === N && s.arm === arm && (rep == null || s.rep === rep))
  return { ok: ss.reduce((a, s) => a + s.recallOk, 0), n: ss.reduce((a, s) => a + s.recallN, 0) }
}
lines.push(
  "",
  "## Recall",
  "",
  "Correct recall answers out of all recall questions (8 per session × scenarios × reps). Per-rep = correct / questions within one repetition.",
  "",
  "| N | arm | correct | questions | per-rep min | per-rep max |",
  "|---|---|---|---|---|---|",
)
for (const N of Ns) {
  for (const arm of ["A", "B", "C"]) {
    const all = recall(N, arm)
    if (!all.n) continue
    const perRep = reps.map((rep) => recall(N, arm, rep))
    const full = perRep.every((p) => p.n)
    const fmt = (p) => `${p.ok}/${p.n}`
    const sorted = [...perRep].sort((a, b) => a.ok / a.n - b.ok / b.n)
    lines.push(`| ${N} | ${arm} | ${all.ok} | ${all.n} | ${full ? fmt(sorted[0]) : "없음"} | ${full ? fmt(sorted.at(-1)) : "없음"} |`)
  }
}
lines.push("")
writeFileSync(join(dir, "range-table.md"), lines.join("\n"))
console.log(lines.join("\n"))
